version: '3.7'
services:
  fluree:
    image: fluree/ledger:v1.0.0-beta11
    container_name: fluree
    networks:
      - default
    ports:
      - '8090:8090'
      - '9790:9790'
    volumes:
      - ${PWD}/.aws:/home/fluree/.aws
